# Gnusto tests: makefile
# Copyright (c) 2003 Thomas Thurman. Distributed under v2 of the GNU GPL.

# FIXME: This should compile "random.z5" which is needed by "random.py".

test:
	clear;python random.py
