#include "nsISupports.idl"
#include "nsIInputStream.idl"
#include "nsIBinaryOutputStream.idl"

////////////////////////////////////////////////////////////////

[scriptable, uuid(bf7a4808-211f-4c6c-827a-c0e5c51e27e1)]
interface gnustoIEngine : nsISupports
{
  void loadStory(in PRUint32 aLength,
		 [size_is(aLength), array] in PRUint8 target);		 

  void loadSavedGame(in PRUint32 aLength,
		     [size_is(aLength), array] in PRUint8 target);		 

  long saveGame();

  void saveGameData(in PRUint32 aLength,
		    [size_is(aLength), array, retval] out PRUint8 target);
		 
  readonly attribute string signature;
  readonly attribute string cvsVersion;

  string effect(in short which);
  void answer(in short which, in string what);

  void run();

  void walk(in string answer);

  string consoleText();

  readonly attribute string architecture;

  attribute short goldenTrail;

  readonly attribute string status;

  short getByte(in long address);
  long getWord(in long address);
  long getUnsignedWord(in long address);
  void setByte(in short value, in long address);
  void setWord(in long value, in long address);
};

////////////////////////////////////////////////////////////////

[scriptable, uuid(56852654-229f-4931-a8c3-942035a6eb1f)]
interface gnustoIZMachine : gnustoIEngine
{
  attribute short piracy;
  attribute short tandy;
};

////////////////////////////////////////////////////////////////
// EOF gnusto-engine.idl
