#  ####  #####  ####  #    # #    #  ####   An Inform program
# #    #   #   #      #    # ##   # #    #  to test the Gnusto
# #    #   #    ####  #    # # #  # #       z-machine. Supplied
# #    #   #        # #    # #  # # #  ###  under the GPL with
# #    #   #   #    # #    # #   ## #    # no warranty. Copyright
#  ####    #    ####   ####  #    #  ####   2003 Thomas Thurman.

COMPILER = /usr/local/bin/inform

otsung.z5: otsung.inf
	$(COMPILER) otsung.inf ../gnusto/content/otsung.z5

